Repository afes-website/front, pull requests merged in 2020-03, with the labels that each got.

#81 fix
  src/App.vue
Labels: bug

#84 #82: パスワード変更
  src/apis/writer/change_password.ts
  src/components/AdminChangePasswordModal.vue
  src/components/WriterChangePasswordModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/views/blog/admin/admin_top.vue
Labels: ASAP, Hot Fix, enhancement

#86 #85: 無限ループ除去
  src/views/blog/admin/revision_list.vue
Labels: bug

#96 #92: path をidに変えた
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
Labels: bug

#94 #59: タイトルがぶっこわれてた
  src/titleMixin.ts
  src/views/Home.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/category_list.vue
  src/views/blog/show_article.vue
  src/views/document.vue
  src/views/policy.vue
Labels: bug

#101 #93-ブログ本文プレビューのはみ出しの処理
  src/views/blog/article_list.vue
Labels: bug

#102 #95: カテゴリがないときの対応
  src/libs/categories.ts
Labels: bug

#104 #88: ログイン後の画面更新
  src/views/blog/admin/admin_top.vue
Labels: bug

#106 #103: 投稿後のページ遷移
  src/views/blog/admin/new_revision.vue
Labels: enhancement

#105 #90-一覧のアイコン修正
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
Labels: bug

#107 #99-vue-gtag
  .env.production
  .github/workflows/deploy_test.yml
  package.json
  src/main.ts
  yarn.lock
Labels: ASAP, enhancement

#98 #87-新型コロナウイルス感染症関連
  src/assets/logo.png
  src/views/Home.vue
  src/views/about.vue
Labels: ASAP, Hot Fix

#83 #82: パスワード変更画面
  src/apis/writer/change_password.ts
  src/components/AdminChangePasswordModal.vue
  src/components/WriterChangePasswordModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/views/blog/admin/admin_top.vue
Labels: enhancement

#111 #109: categoriesをexport
  src/App.vue
  src/libs/categories.ts
  src/views/blog/admin/path_list.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
Labels: improve

#119 #110: カテゴリを選択式に
  src/App.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/show_article.vue
Labels: enhancement

#122 #108: 内部生向けカテゴリ
  src/App.vue
  src/libs/categories.ts
  src/views/blog/admin/manage_path.vue
Labels: enhancement

#114 #112-fix vue-gtag
  .env.production
  .github/workflows/deploy_test.yml
  src/main.ts
Labels: ASAP, bug

#123 #89: 全記事表示
  src/App.vue
  src/router/index.ts
  src/views/Home.vue
  src/views/blog/article_list.vue
  src/views/blog/category_list.vue
Labels: enhancement

#127 #124: PWA無効化
  package.json
  src/main.ts
  src/registerServiceWorker.ts
  yarn.lock
Labels: improve

#126 #120 背景の画像サイズを変更
  src/assets/back.jpg
Labels: discuss, improve

#128 #121-ヘッダーのアイコンがはみ出る問題
  src/App.vue
  src/assets/sns/azabu.svg
Labels: bug

#125 Deploy
  .env.production
  .github/workflows/deploy_test.yml
  package.json
  src/App.vue
  src/assets/back.jpg
  src/assets/sns/azabu.svg
  src/libs/categories.ts
  src/main.ts
  src/registerServiceWorker.ts
  src/router/index.ts
  src/titleMixin.ts
  src/views/Home.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/category_list.vue
  src/views/blog/show_article.vue
  src/views/document.vue
  src/views/policy.vue
  yarn.lock
Labels: Deploy, WIP

#137 #133: サイドバーを隠す
  src/App.vue
Labels: bug

#136 #132: ページタイトルが変わらなかった
  src/views/blog/article_list.vue
Labels: bug

#135 #118: 画像アップロード
  src/apis/images/@utils.ts
  src/apis/images/index.ts
  src/components/ImageUploadModal.vue
  src/views/blog/admin/new_revision.vue
Labels: enhancement

#147 #100-引用css
  src/assets/sass/main.scss
Labels: enhancement

#139 #116 manage_pathのタイトル
  src/views/blog/admin/manage_path.vue
Labels: improve

#140 #138: markdown拡張をいくつか消す
  package.json
  src/libs/markdown.ts
  yarn.lock
Labels: improve

#141 #117: サイドメニュー表示条件の変更
  src/App.vue
Labels: improve

#149 #97-アイキャッチ
  src/assets/no-image.svg
  src/views/blog/article_list.vue
Labels: enhancement

#153 #97-2-アイキャッチ画像が復活してた
  src/views/blog/article_list.vue
Labels: ASAP, bug

#151 #40-お問い合わせフォーム
  src/App.vue
  src/router/index.ts
  src/views/contact.vue
Labels: enhancement

#145 404ページ
  src/App.vue
  src/assets/404.svg
  src/router/index.ts
  src/views/NotFound.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/show_article.vue
Labels: enhancement

#155 #154: sort articles
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
Labels: bug

#148 #115: 行クリック
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
Labels: discuss

#156 Release/1.2.0 into master
  package.json
  src/App.vue
  src/apis/images/@utils.ts
  src/apis/images/index.ts
  src/assets/404.svg
  src/assets/no-image.svg
  src/assets/sass/main.scss
  src/components/ImageUploadModal.vue
  src/libs/markdown.ts
  src/router/index.ts
  src/views/NotFound.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  yarn.lock
Labels: Deploy

#157 Release/1.2.0 into dev
  package.json
Labels: Deploy

#160 #146 mainを拡げる
  src/assets/sass/main.scss
  src/assets/sass/wide_main_box.scss
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
Labels: enhancement

#161 #60-OGP･SEO #78-title
  public/img/thumbnail.jpg
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/titleMixin.ts
Labels: discuss, enhancement

#163 #162-[mobile] footer幅がおかしい
  src/App.vue
Labels: bug

#159 #129: improve readme
  README.md
Labels: improve

#164 #131-パンくずリスト
  src/components/Breadcrumb.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  src/views/document.vue
  src/views/policy.vue
Labels: enhancement

#166 Release 1.3.0
  README.md
  package.json
  public/img/thumbnail.jpg
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/App.vue
  src/assets/sass/main.scss
  src/assets/sass/wide_main_box.scss
  src/components/Breadcrumb.vue
  src/titleMixin.ts
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  src/views/document.vue
  src/views/policy.vue
  yarn.lock
Labels: Release

#167 Relase 1.3.0 (to dev)
  package.json
Labels: Release

#170 #168-Twitterbotがクロールできてなかった
  public/robots.txt
Labels: bug

#171 #150-create padding in bottom of main
  src/App.vue
Labels: improve

#172 #130-share button
  src/components/ShareButtons.vue
  src/views/blog/show_article.vue
Labels: enhancement

#174 #169-PC: 60% mobile: 100%
  src/App.vue
  src/assets/sass/main.scss
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/show_article.vue
Labels: improve

#177 #173- make preview realistic
  src/views/blog/admin/new_revision.vue
Labels: enhancement

#178 #176-replace img with svg
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/sns/azabu.svg
  src/assets/sns/instagram.png
  src/assets/sns/instagram.svg
  src/assets/sns/twitter.svg
  src/views/Home.vue
Labels: improve

#180 #179: jwtのuidキーを変更可能に
  src/libs/auth/admin_auth.ts
  src/libs/auth/jwt.ts
  src/libs/auth/writer_auth.ts
Labels: bug

#182 Release/1.4.0
  package.json
  public/robots.txt
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/sass/main.scss
  src/assets/sns/azabu.svg
  src/assets/sns/instagram.png
  src/assets/sns/instagram.svg
  src/assets/sns/twitter.svg
  src/components/ShareButtons.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/jwt.ts
  src/libs/auth/writer_auth.ts
  src/views/Home.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/show_article.vue
Labels: Release

#183 Release 1.4.0 to dev
  package.json
Labels: Release

#187 #186: upgrade packages
  .eslintrc.js
  aspida.config.js
  babel.config.js
  package.json
  src/App.vue
  src/apis/admin/change_password.ts
  src/apis/admin/login.ts
  src/apis/admin/user.ts
  src/apis/blog/articles/_id@string.ts
  src/apis/blog/articles/index.ts
  src/apis/blog/revisions/_id@number/accept.ts
  src/apis/blog/revisions/_id@number/index.ts
  src/apis/blog/revisions/_id@number/reject.ts
  src/apis/blog/revisions/index.ts
  src/apis/images/index.ts
  src/apis/writer/change_password.ts
  src/apis/writer/login.ts
  src/apis/writer/user.ts
  src/components/AdminChangePasswordModal.vue
  src/components/Breadcrumb.vue
  src/components/ImageUploadModal.vue
  src/components/ShareButtons.vue
  src/components/WriterChangePasswordModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/libs/categories.ts
  src/main.ts
  src/router/index.ts
  src/types/markdown-it-plugins.d.ts
  src/views/Home.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  src/views/document.vue
  src/views/policy.vue
  tests/unit/.eslintrc.js
  tests/unit/example.spec.ts
  vue.config.js
  yarn.lock
Labels: dependencies

#185 #181: スタイルの改善
  src/App.vue
  src/assets/sass/main.scss
Labels: bug, improve

#184 #175: ブログ編集ボタン
  src/views/blog/admin/new_revision.vue
  src/views/blog/show_article.vue
Labels: enhancement

#190 #189: 動的OGP
  public/.htaccess
  public/dynamic_ogp.php
  public/index.html
Labels: enhancement

#192 #191: paginationのページ保存
  src/views/blog/article_list.vue
Labels: enhancement

#193 #188 再デザイン
  package.json
  src/App.vue
  src/assets/back.jpg
  src/assets/logo_white.svg
  src/assets/sass/_variables.scss
  src/assets/sass/main.scss
  src/assets/sass/wide_main_box.scss
  src/views/Home.vue
  src/views/NotFound.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  src/views/document.vue
  src/views/policy.vue
  yarn.lock
Labels: enhancement
