Repository afes-website/front, pull requests merged in 2020-05, with the labels that each got.

#246 #245: upgrade packages
  package.json
  src/views/blog/admin/new_revision.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  yarn.lock
Labels: dependencies

#243 #241 update icons
  public/android-touch-icon.png
  public/apple-touch-icon.png
  public/dynamic_icon.php
  public/favicon.ico
  public/index.html
  public/manifest.json
Labels: design, enhancement

#250 #249 寄稿 ogp
  public/dynamic_ogp.php
Labels: bug

#248 #247 markdownの処理をまとめた
  src/libs/markdown.ts
  src/views/blog/admin/new_revision.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
Labels: refactor

#251 Release/1.6.2
  .eslintrc.js
  package.json
  public/android-touch-icon.png
  public/apple-touch-icon.png
  public/dynamic_icon.php
  public/dynamic_ogp.php
  public/favicon.ico
  public/index.html
  public/manifest.json
  rules/vue-template-simple-expr.js
  src/App.vue
  src/apis/blog/revisions/contrib/@types.ts
  src/apis/blog/revisions/contrib/index.ts
  src/assets/sass/main.scss
  src/components/FetchStatusIcon.vue
  src/components/ShareButtons.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/libs/markdown.ts
  src/router/index.ts
  src/views/Home.vue
  src/views/NotFound.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  yarn.lock
Labels: Release

#252 update 1.6.2 to dev
  package.json
Labels: Release

#254 #253 カテゴリー取得がしんでた to master
  package.json
  src/views/Home.vue
Labels: Hot Fix

#255 #253 category取得が死んでた to dev
  package.json
  src/views/Home.vue
Labels: Hot Fix

#257 #256 無期限延期のお知らせ
  package.json
  public/dynamic_ogp.php
  public/img/thumbnail.png
  public/manifest.json
  src/assets/logo.svg
  src/assets/logo_white.svg
  src/views/Home.vue
Labels: Hot Fix

#258 #256 無期限延期
  package.json
  public/dynamic_ogp.php
  public/img/thumbnail.png
  public/manifest.json
  src/assets/logo.svg
  src/assets/logo_white.svg
  src/views/Home.vue
Labels: Hot Fix

#260 #259 無期限延期に関する構造化データ
  src/components/SpecialAnnouncement.vue
  src/views/Home.vue
Labels: enhancement

#261 Release/1.6.5
  package.json
  src/components/SpecialAnnouncement.vue
  src/views/Home.vue
Labels: Release

#262 Release/1.6.5 to dev
  package.json
Labels: Release

#265 #263 構造化データのご機嫌をとる
  src/components/SpecialAnnouncement.vue
Labels: improve

#266 #264 notebot を追加 / note:card 対応
  public/dynamic_ogp.php
  public/index.html
Labels: improve

#267 Release/1.6.6
  package.json
  public/dynamic_ogp.php
  public/index.html
  src/components/SpecialAnnouncement.vue
Labels: Release

#268 Update 1.6.6 to dev
  package.json
Labels: Release

#270 #269 JWT有効性ちぇっく
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
Labels: bug
