Repository afes-website/front, pull requests merged in 2020-08, with the labels that each got.

#314 #306 記事一覧に読むのにかかる時間を表示した
  src/libs/markdown.ts
  src/views/blog/admin/new_revision.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  src/views/blog/show_article.vue
Labels: enhancement

#324 Feature/#323 upgrade packages
  .eslintrc.js
  package.json
  src/components/AdminChangePasswordModal.vue
  src/components/AdminLoginModal.vue
  src/components/ImageUploadModal.vue
  src/components/ShareButtons.vue
  src/components/WriterChangePasswordModal.vue
  src/components/WriterLoginModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/admin_auth_eventhub.ts
  src/libs/auth/writer_auth.ts
  src/libs/auth/writer_auth_eventhub.ts
  src/views/Home.vue
  src/views/about.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/new_contrib.vue
  src/views/document.vue
  src/views/policy.vue
  vue.config.js
  yarn.lock
Labels: dependencies

#321 Update v1.7.3
  .eslintrc.js
  package.json
  src/components/AdminChangePasswordModal.vue
  src/components/AdminLoginModal.vue
  src/components/ImageUploadModal.vue
  src/components/ShareButtons.vue
  src/components/WriterChangePasswordModal.vue
  src/components/WriterLoginModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/admin_auth_eventhub.ts
  src/libs/auth/writer_auth.ts
  src/libs/auth/writer_auth_eventhub.ts
  src/libs/markdown.ts
  src/views/Home.vue
  src/views/about.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  src/views/blog/show_article.vue
  src/views/document.vue
  src/views/policy.vue
  vue.config.js
  yarn.lock
Labels: Release

#322 Update v1.7.3 to dev
  package.json
Labels: Release
