Repository afes-website/front, pull requests merged in 2020-02, with the labels that each got.

#3 #1-ページテンプレートの作成
  package.json
  public/img/Twitter_Logo_Blue.svg
  public/img/azabu_icon.svg
  public/img/instagram.png
  src/App.vue
  src/assets/sass/_variables.scss
  src/assets/sass/main.scss
  yarn.lock
Labels: enhancement

#8 #7-mainの上の隙間を削除
  src/App.vue
Labels: bug

#13 #12-FontAwesomeのfar,fabを追加
  package.json
  src/main.ts
  yarn.lock
Labels: ASAP, enhancement

#11 #9-.main-wrapperの外でスクロールできない
  src/App.vue
Labels: bug

#17 #4-トップページの作成
  src/assets/top.jpg
  src/components/TopPageButton.vue
  src/views/Home.vue
Labels: enhancement

#18 #5-固定ページの作成
  src/App.vue
  src/router/index.ts
  src/views/About.vue
  src/views/about.vue
  src/views/access.vue
  src/views/policy.vue
Labels: enhancement

#23 #22-wrap style that should be scoped
  src/App.vue
Labels: bug

#24 #21-z-indexの反乱を鎮圧
  src/App.vue
  src/components/TopPageButton.vue
Labels: bug

#27 #25-構造化タグをちゃんとした
  public/index.html
  src/App.vue
  src/views/Home.vue
Labels: enhancement

#26 #20-PC版全てのページに背景画像をセット
  src/App.vue
  src/assets/back.jpg
  src/assets/sass/main.scss
  src/views/Home.vue
  src/views/about.vue
  src/views/access.vue
  src/views/policy.vue
Labels: enhancement

#38 Fix #34 : 環境設定の追加
  .env
  .env.development
  .env.production
  src/main.ts
Labels: enhancement

#39 #29-SNSアイコンにリンクぺたり
  src/App.vue
  src/assets/sns/azabu.svg
  src/assets/sns/instagram.png
  src/assets/sns/twitter.svg
Labels: enhancement

#35 #15-共通css･フォント関連
  src/App.vue
  src/assets/sass/main.scss
  src/components/TopPageButton.vue
  src/views/Home.vue
  src/views/about.vue
  src/views/access.vue
Labels: enhancement

#41 Feature/#37 upgrade packages
  .eslintrc.js
  package.json
  yarn.lock
Labels: improve

#44 #42 : install js-cookie
  package.json
  yarn.lock
Labels: improve

#46 #43: fix eslint errors
  .eslintrc.js
  src/App.vue
  src/shims-tsx.d.ts
  src/titleMixin.ts
Labels: ASAP, bug

#48 #47 install @types/js-cookie
  package.json
  yarn.lock
Labels: bug

#49 #45: setup api
  aspida.config.js
  package.json
  yarn.lock
Labels: enhancement

#53 #52: api:buildコマンドを追加
  package.json
Labels: enhancement

#51 #50 自動デプロイ/テスト
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_test.yml
  .github/workflows/test_pull.yml
Labels: enhancement

#55 #54: env local
  .github/workflows/deploy_test.yml
  .github/workflows/test_pull.yml
Labels: bug

#61 #58: warningで落ちるようにした
  .github/workflows/test_pull.yml
Labels: bug

#57 #10: 管理者ログイン
  src/App.vue
  src/apis/@types.ts
  src/apis/admin/change_password.ts
  src/apis/admin/login.ts
  src/apis/admin/user.ts
  src/components/AdminLoginModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/admin_auth_eventhub.ts
  src/libs/auth/index.ts
  src/libs/auth/jwt.ts
Labels: enhancement

#66 #28,56-aboutページ内容追加･修正
  src/assets/about.jpg
  src/views/about.vue
Labels: bug, enhancement

#68 #64: modalとかなおした
  src/App.vue
  src/assets/sass/main.scss
Labels: bug

#71 #65: リンクの宛先の修正
  src/App.vue
Labels: bug

#69 #62: .env.localが読まれなかった
  .github/workflows/deploy_test.yml
Labels: bug

#70 #63 隠さなくていいやつをソース直書きした
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_test.yml
Labels: improve

#67 #30-ページ遷移時のスクロール位置修正
  src/router/index.ts
Labels: bug

#74 #31-favicon それだけ
  public/favicon.ico
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
Labels: enhancement

#73 #19-ロゴ入れ
  src/App.vue
  src/assets/logo.png
  src/views/Home.vue
Labels: enhancement

#80 hotfix: make link absolute and use router
  src/App.vue
Labels: Hot Fix, bug
