Repository afes-website/front, pull requests merged in 2020-11, with the labels that each got.

#390 feat: change link to use after fes
  src/views/exhibition/exh_show.vue
Labels: ASAP

#392 #386 トップページとその周辺の更新
  public/dynamic_ogp.php
  src/App.vue
  src/assets/back.jpg
  src/components/TopPageButton.vue
  src/main.ts
  src/views/Home.vue
Labels: design, enhancement

#391 #387 renderer 周りの修正
  src/components/MarkdownRenderer.vue
  src/libs/markdown.ts
  src/libs/markdown_embed.ts
  src/types/twitter-widgets.d.ts
  src/views/admin/draft/draft_preview.vue
Labels: bug

#393 [hotfix] #388 フォームリンクの差し替え to dev
  src/views/exhibition/exh_show.vue
Labels: Hot Fix, enhancement

#394 #389 あなたの記事リクエスト一覧を filter
  src/views/admin/blog/revision_list.vue
Labels: bug

#395 #385 admin も draft を post できるようにした
  src/views/admin/draft/draft_post.vue
Labels: bug

#396 Release v2.2.7
  package.json
  public/dynamic_ogp.php
  src/App.vue
  src/assets/back.jpg
  src/components/MarkdownRenderer.vue
  src/components/TopPageButton.vue
  src/libs/markdown.ts
  src/libs/markdown_embed.ts
  src/main.ts
  src/types/twitter-widgets.d.ts
  src/views/Home.vue
  src/views/admin/blog/revision_list.vue
  src/views/admin/draft/draft_post.vue
  src/views/admin/draft/draft_preview.vue
Labels: Release

#397 Release v2.2.7 to dev
  package.json
Labels: Release

#399 #398 bg image をいろいろ改善
  package.json
  src/assets/back.jpg
  src/views/Home.vue
Labels: Hot Fix

#400 #398 bg image をいろいろ改善 to dev
  package.json
  src/assets/back.jpg
  src/views/Home.vue
Labels: Hot Fix

#403 #402 トップページのロゴを上下中央にした
  package.json
  src/views/Home.vue
Labels: Hot Fix, design

#404 #402 トップページのロゴを上下中央にした to dev
  package.json
  src/views/Home.vue
Labels: Hot Fix, design

#406 #405 オンライン展示終了 サブドメイン移行
  .env.production
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_test.yml
  package.json
  src/App.vue
  src/components/ShareButtons.vue
  src/router/index.ts
  src/views/Home.vue
  src/views/admin/admin_top.vue
Labels: Hot Fix

#407 #405 オンライン展示終了 サブドメイン移行 to dev
  .env.production
  .github/workflows/deploy_prod.yml
  .github/workflows/deploy_test.yml
  package.json
  src/App.vue
  src/components/ShareButtons.vue
  src/router/index.ts
  src/views/Home.vue
  src/views/admin/admin_top.vue
Labels: Hot Fix
