Repository afes-website/front, pull requests merged in 2020-04, with the labels that each got.

#198 #197 Bootstrap方面の変更が不十分だった
  src/assets/sass/main.scss
  src/views/blog/admin/admin_top.vue
Labels: ASAP, bug

#196 #194-ひとまとめ
  package.json
  src/libs/string_date.ts
  src/views/Home.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  yarn.lock
Labels: refactor

#200 #195 日付の表示形式を変えた
  src/libs/string_date.ts
Labels: enhancement

#201 Release 1.5.0
  package.json
Labels: Release

#205 Release 1.5.0
  .eslintrc.js
  aspida.config.js
  babel.config.js
  package.json
  public/.htaccess
  public/dynamic_ogp.php
  public/index.html
  src/App.vue
  src/apis/admin/change_password.ts
  src/apis/admin/login.ts
  src/apis/admin/user.ts
  src/apis/blog/articles/_id@string.ts
  src/apis/blog/articles/index.ts
  src/apis/blog/revisions/_id@number/accept.ts
  src/apis/blog/revisions/_id@number/index.ts
  src/apis/blog/revisions/_id@number/reject.ts
  src/apis/blog/revisions/index.ts
  src/apis/images/index.ts
  src/apis/writer/change_password.ts
  src/apis/writer/login.ts
  src/apis/writer/user.ts
  src/assets/back.jpg
  src/assets/logo_white.svg
  src/assets/sass/_variables.scss
  src/assets/sass/main.scss
  src/assets/sass/wide_main_box.scss
  src/components/AdminChangePasswordModal.vue
  src/components/Breadcrumb.vue
  src/components/ImageUploadModal.vue
  src/components/ShareButtons.vue
  src/components/WriterChangePasswordModal.vue
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/libs/categories.ts
  src/libs/string_date.ts
  src/main.ts
  src/router/index.ts
  src/types/markdown-it-plugins.d.ts
  src/views/Home.vue
  src/views/NotFound.vue
  src/views/about.vue
  src/views/access.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  src/views/document.vue
  src/views/policy.vue
  tests/unit/.eslintrc.js
  tests/unit/example.spec.ts
  vue.config.js
  yarn.lock
Labels: Release

#208 #207 TopPageButton の色を更新し忘れた
  package.json
  src/components/TopPageButton.vue
Labels: Hot Fix

#203 #202: Bootstrapはrootへ。
  src/assets/sass/main.scss
Labels: bug

#204 #199: path制約
  src/views/blog/admin/new_revision.vue
Labels: enhancement

#209 #206 更新情報カテゴリ追加
  public/dynamic_ogp.php
  src/libs/categories.ts
Labels: enhancement

#210 #207 to dev
  package.json
  src/components/TopPageButton.vue
Labels: Hot Fix

#211 Release 1.5.2
  package.json
  public/dynamic_ogp.php
  src/assets/sass/main.scss
  src/libs/categories.ts
  src/views/blog/admin/new_revision.vue
Labels: Release

#212 Release 1.5.2 to dev
  package.json
Labels: Release

#218 #214: 画像アップロードができるようになった
  src/apis/images/index.ts
Labels: Hot Fix, bug

#219 画像うp -> develop
  src/apis/images/index.ts
Labels: Hot Fix, bug

#217 #215 set max-width revision preview
  src/views/blog/admin/revision_preview.vue
Labels: bug

#220 ブログ記事の Allow・内部生向けの Disallow
  public/robots.txt
Labels: improve

#221 Release 1.5.3
  package.json
  public/robots.txt
  src/views/blog/admin/revision_preview.vue
Labels: Release

#222 Release 1.5.3 to dev
  package.json
Labels: Release

#224 #223 動的 og:image の追加 / 静的 og:image の更新
  public/dynamic_ogp.php
  public/img/thumbnail.jpg
  public/img/thumbnail.png
  src/views/blog/admin/new_revision.vue
Labels: enhancement

#227 #226: Revisionのユーザ情報をobjectのやつにした
  src/apis/blog/revisions/@types.ts
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/revision_preview.vue
Labels: ASAP, bug

#228 #225 get category from api
  public/dynamic_ogp.php
  src/App.vue
  src/apis/blog/categories/@types.ts
  src/apis/blog/categories/index.ts
  src/components/Breadcrumb.vue
  src/libs/categories.ts
  src/views/Home.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
Labels: enhancement

#229 Release 1.6.0
  package.json
  public/dynamic_ogp.php
  public/img/thumbnail.jpg
  public/img/thumbnail.png
  src/App.vue
  src/apis/blog/categories/@types.ts
  src/apis/blog/categories/index.ts
  src/apis/blog/revisions/@types.ts
  src/components/Breadcrumb.vue
  src/libs/categories.ts
  src/views/Home.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
Labels: Release

#230 update 1.6.0 to dev
  package.json
Labels: Release

#235 Hotfix/#234 api url dev
  package.json
  public/dynamic_ogp.php
Labels: Hot Fix

#236 Hotfix/#234 api url dev
  package.json
  public/dynamic_ogp.php
Labels: Hot Fix

#238 #233 色の統一とかデザイン関連とか
  src/App.vue
  src/assets/sass/main.scss
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/show_article.vue
Labels: enhancement

#237 #158 寄稿フォーム
  src/apis/blog/revisions/contrib/@types.ts
  src/apis/blog/revisions/contrib/index.ts
  src/router/index.ts
  src/views/blog/new_contrib.vue
Labels: enhancement

#239 #231 Vueテンプレート内の式をなくす
  .eslintrc.js
  package.json
  rules/vue-template-simple-expr.js
  src/App.vue
  src/components/FetchStatusIcon.vue
  src/components/ShareButtons.vue
  src/views/Home.vue
  src/views/NotFound.vue
  src/views/blog/admin/admin_top.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  src/views/blog/show_article.vue
  src/views/contact.vue
  yarn.lock
Labels: improve

#242 #240: JWTの本当の有効性を確認
  src/libs/auth/admin_auth.ts
  src/libs/auth/writer_auth.ts
  src/views/blog/admin/admin_top.vue
Labels: bug
