Repository afes-website/front, pull requests merged in 2020-10, with the labels that each got.

#334 #333 403 チェックがあるページの document.title が壊れる不具合を修正
  src/components/Forbidden.vue
  src/views/blog/admin/manage_path.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/admin/path_list.vue
  src/views/blog/admin/revision_list.vue
  src/views/blog/admin/revision_preview.vue
Labels: bug

#341 #340 sanitizer を消す
  package.json
  src/libs/markdown.ts
  src/types/markdown-it-plugins.d.ts
  yarn.lock
Labels: enhancement

#342 #325 ブログ html 対応 & 埋め込み対応
  package.json
  src/assets/sass/main.scss
  src/components/EmbedModal.vue
  src/components/ImageUploadModal.vue
  src/components/MarkdownEditor.vue
  src/components/MarkdownRenderer.vue
  src/libs/markdown.ts
  src/libs/markdown_embed.ts
  src/main.ts
  src/types/twitter-widgets.d.ts
  src/views/blog/admin/new_revision.vue
  src/views/blog/article_list.vue
  src/views/blog/new_contrib.vue
  src/views/blog/show_article.vue
  yarn.lock
Labels: enhancement

#343 #338 Integrated Markdown Editor
  src/components/IntegratedMarkdownEditor.vue
  src/components/MarkdownEditor.vue
  src/views/blog/admin/new_revision.vue
  src/views/blog/new_contrib.vue
Labels: enhancement

#335 #332 オンライン展示関連の実装
  package.json
  src/App.vue
  src/assets/sass/_variables.scss
  src/assets/sass/main.scss
  src/components/Breadcrumb.vue
  src/components/CommentList.vue
  src/components/DraftTable.vue
  src/components/ExhibitionCard.vue
  src/components/FetchStatusIcon.vue
  src/components/Forbidden.vue
  src/components/IntegratedMarkdownEditor.vue
  src/libs/auth/auth.ts
  src/libs/string_date.ts
  src/router/index.ts
  src/views/admin/admin_top.vue
  src/views/admin/blog/manage_path.vue
  src/views/admin/blog/new_revision.vue
  src/views/admin/blog/path_list.vue
  src/views/admin/blog/revision_list.vue
  src/views/admin/blog/revision_preview.vue
  src/views/admin/draft/draft_list.vue
  src/views/admin/draft/draft_manage.vue
  src/views/admin/draft/draft_post.vue
  src/views/admin/draft/draft_preview.vue
  src/views/admin/exh/exh_list.vue
  src/views/admin/exh/exh_manage.vue
  src/views/admin/login.vue
  src/views/blog/admin/admin_top.vue
  yarn.lock
Labels: enhancement

#346 Release v2.2.0 to develop
  package.json
Labels: Release

#350 #348 draft table 内で exh id による絞り込み
  src/components/DraftTable.vue
  src/views/admin/exh/exh_manage.vue
Labels: bug

#349 #347 教員も preview を見れるように
  src/views/admin/draft/draft_preview.vue
Labels: bug

#351 #281 サイドバーをスクロール可能にしたぞ！！！！！
  src/App.vue
Labels: bug

#356 #354 Preview ボタンを exh list から消した
  src/views/admin/exh/exh_list.vue
Labels: bug

#355 #342 draft manage の preview ボタンを独立させた
  src/views/admin/draft/draft_manage.vue
Labels: enhancement

#357 #353 Preview を新規タブで開く
  src/components/DraftTable.vue
  src/views/admin/draft/draft_manage.vue
Labels: enhancement

#358 Release v2.2.1
  package.json
  src/App.vue
  src/components/DraftTable.vue
  src/views/admin/draft/draft_manage.vue
  src/views/admin/draft/draft_preview.vue
  src/views/admin/exh/exh_list.vue
  src/views/admin/exh/exh_manage.vue
Labels: Release

#359 Release v2.2.1 to dev
  package.json
Labels: Release

#362 [hotfix] #361 wrapper に z-index をつけた
  package.json
  src/App.vue
Labels: Hot Fix

#363 [hotfix to dev] #361 wrapper に z-index をつけた
  package.json
  src/App.vue
Labels: Hot Fix

#368 #337 オンライン展示 外部視点
  src/App.vue
  src/components/Breadcrumb.vue
  src/components/ExhibitionCard.vue
  src/router/index.ts
  src/views/exhibition/exh_list.vue
  src/views/exhibition/exh_show.vue
  yarn.lock
Labels: enhancement

#369 #337-2 オンライン展示一覧 スマホからのアクセス
  src/views/Home.vue
Labels: enhancement

#370 #364 iOS で header が表示されないバグの修正？
  src/App.vue
Labels: bug

#371 Release v2.2.3
  package.json
  src/App.vue
  src/components/Breadcrumb.vue
  src/components/ExhibitionCard.vue
  src/router/index.ts
  src/views/Home.vue
  src/views/exhibition/exh_list.vue
  src/views/exhibition/exh_show.vue
  yarn.lock
Labels: Release

#372 Release v2.2.3 to dev
  package.json
Labels: Release

#374 [hotfix] トップページ文章更新
  package.json
  src/views/Home.vue
Labels: Hot Fix

#375 [hotfix] トップページ文章更新
  package.json
  src/views/Home.vue
Labels: Hot Fix

#378 [hotfix] #376 ogp to dev
  public/dynamic_ogp.php
Labels: Hot Fix

#380 youtube video id capture to dev
  package.json
  src/components/EmbedModal.vue
Labels: Hot Fix

#379 youtube video id capture
  package.json
  src/components/EmbedModal.vue
Labels: Hot Fix

#383 b-alert/b-link
  package.json
  src/views/exhibition/exh_show.vue
Labels: Hot Fix

#384 b-alert/b-link to dev
  package.json
  src/views/exhibition/exh_show.vue
Labels: Hot Fix
